name: Publish to NPM

on:
  push:
    branches: [main]


permissions:
  contents: write
  id-token: write # Required for trusted publishing

jobs:
  release:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # We need the full history for version calculation
          fetch-depth: 0

      - name: Install Node.js per package.json
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9
          run_install: true

      - name: Update npm # To ensure npm 11.5.1 or later is installed for Trusted publishing
        shell: bash
        run: npm install -g npm@latest

      - name: "Git Config"
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"  

      - name: Publish minor release (using OIDC trusted publishing)
        shell: bash
        run: pnpm run ci:publish:latest