name: Publish to NPM

on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write # Required for trusted publishing

jobs:
  call-publish:
    uses: ./.github/workflows/reusable_publish_dev.yml
    secrets:
      MY_GH_RELEASE_TOKEN: ${{ secrets.MY_GH_RELEASE_TOKEN }}
