name: Publish to NPM

on:
  push:
    branches: [main]


permissions:
  contents: write
  id-token: write # Required for trusted publishing

jobs:
  release:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # We need the full history for version calculation
          fetch-depth: 0

      - name: Install Node.js per package.json
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Publish minor release (using OIDC trusted publishing)
        run: npx lerna publish minor --force-publish -y --push=false --gitTagVersion=false